
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:24:36 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'pin_sasebo_giii_k7.ucf'
####################################################################################

# -------------------------------------------------------------------------
# Pin assignment of Kintex-7 on SASEBO-GIII
#
# File name   : pin_sasebo_giii_k7.v
# Version     : 1.1
# Created     : APR/02/2012
# Last update : APR/25/2013
# Desgined by : Toshihiro Katashita
#
#
# Copyright (C) 2012, 2013 AIST
#
# By using this code, you agree to the following terms and conditions.
#
# This code is copyrighted by AIST ("us").
#
# Permission is hereby granted to copy, reproduce, redistribute or
# otherwise use this code as long as: there is no monetary profit gained
# specifically from the use or reproduction of this code, it is not sold,
# rented, traded or otherwise marketed, and this copyright notice is
# included prominently in any copy made.
#
# We shall not be liable for any damages, including without limitation
# direct, indirect, incidental, special or consequential damages arising
# from the use of this code.
#
# When you publish any results arising from the use of this code, we will
# appreciate it if you can cite our webpage.
# (http://www.risec.aist.go.jp/project/sasebo/)
# -------------------------------------------------------------------------

#-------------------------------------------------------------------------
# Please note that this file is different from the file provided by the authors
# named above. Several constraints have been added, removed, or modified
# in order to meet the requirements of this design. Therefore, this file is
# an adaptation of the original file.
# -------------------------------------------------------------------------

#================================================　Timing constraint

#NET "lbus_clkn" TNM_NET = "clkin_grp";
#TIMESPEC "TS_clkin" = PERIOD : "clkin_grp" : 41.666 ns HIGH 50.0%;

create_clock -period 50 -name lbus_clkn [get_ports lbus_clkn]

#================================================ Pin assignment
#------------------------------------------------ Clock, reset, LED, and SW.
#################
# CLOCK / RESET #
#################

#NET "osc_en_b" LOC="J8" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets osc_en_b]
set_property PACKAGE_PIN J8 [get_ports osc_en_b]
set_property IOSTANDARD LVCMOS25 [get_ports osc_en_b]
#set_property DRIVE 2 [get_ports osc_en_b]
#set_property SLEW QUIETIO [get_ports osc_en_b]

#######
# LED #
#######

#NET "led<9>" LOC="G20" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets {led[9]}]
set_property PACKAGE_PIN G20 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[9]}]
#set_property DRIVE 2 [get_ports {led[9]}]
#set_property SLEW QUIETIO [get_ports {led[9]}]

#NET "led<8>" LOC="L19" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets {led[8]}]
set_property PACKAGE_PIN L19 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[8]}]
#set_property DRIVE 2 [get_ports {led[8]}]
#set_property SLEW QUIETIO [get_ports {led[8]}]

#NET "led<7>" LOC="K18" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets {led[7]}]
set_property PACKAGE_PIN K18 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[7]}]
#set_property DRIVE 2 [get_ports {led[7]}]
#set_property SLEW QUIETIO [get_ports {led[7]}]

#NET "led<6>" LOC="H19" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets {led[6]}]
set_property PACKAGE_PIN H19 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[6]}]
#set_property DRIVE 2 [get_ports {led[6]}]
#set_property SLEW QUIETIO [get_ports {led[6]}]

#NET "led<5>" LOC="K15" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets {led[5]}]
set_property PACKAGE_PIN K15 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[5]}]
#set_property DRIVE 2 [get_ports {led[5]}]
#set_property SLEW QUIETIO [get_ports {led[5]}]

#NET "led<4>" LOC="P16" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets {led[4]}]
set_property PACKAGE_PIN P16 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[4]}]
#set_property DRIVE 2 [get_ports {led[4]}]
#set_property SLEW QUIETIO [get_ports {led[4]}]

#NET "led<3>" LOC="T19" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets {led[3]}]
set_property PACKAGE_PIN T19 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[3]}]
#set_property DRIVE 2 [get_ports {led[3]}]
#set_property SLEW QUIETIO [get_ports {led[3]}]

#NET "led<2>" LOC="T18" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets {led[2]}]
set_property PACKAGE_PIN T18 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[2]}]
#set_property DRIVE 2 [get_ports {led[2]}]
#set_property SLEW QUIETIO [get_ports {led[2]}]

#NET "led<1>" LOC="H12" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets {led[1]}]
set_property PACKAGE_PIN H12 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[1]}]
#set_property DRIVE 2 [get_ports {led[1]}]
#set_property SLEW QUIETIO [get_ports {led[1]}]

#NET "led<0>" LOC="H11" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets {led[0]}]
set_property PACKAGE_PIN H11 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[0]}]
#set_property DRIVE 2 [get_ports {led[0]}]
#set_property SLEW QUIETIO [get_ports {led[0]}]

########
# GPIO #
########

#NET "gpio_startn" LOC="D19" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets gpio_startn]
set_property PACKAGE_PIN D19 [get_ports gpio_startn]
set_property IOSTANDARD LVCMOS25 [get_ports gpio_startn]
#set_property DRIVE 2 [get_ports gpio_startn]
#set_property SLEW QUIETIO [get_ports gpio_startn]

#NET "gpio_endn"   LOC="N17" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets gpio_endn]
set_property PACKAGE_PIN N17 [get_ports gpio_endn]
set_property IOSTANDARD LVCMOS25 [get_ports gpio_endn]
#set_property DRIVE 2 [get_ports gpio_endn]
#set_property SLEW QUIETIO [get_ports gpio_endn]

#NET "gpio_exec"   LOC="N16" |IOSTANDARD=LVCMOS25 |SLEW=QUIETIO |DRIVE=2 |TIG;

set_false_path -through [get_nets gpio_exec]
set_property PACKAGE_PIN N16 [get_ports gpio_exec]
set_property IOSTANDARD LVCMOS25 [get_ports gpio_exec]
#set_property DRIVE 2 [get_ports gpio_exec]
#set_property SLEW QUIETIO [get_ports gpio_exec]

#------------------------------------------------ Local bus
#############################################
# Spartan-6 HPIC (LVCMOS15, SSTL15 or HTSL) #
#############################################

#NET "lbus_clkn"   LOC="AB11" |IOSTANDARD=LVCMOS15;

set_property PACKAGE_PIN AB11 [get_ports lbus_clkn]
set_property IOSTANDARD LVCMOS15 [get_ports lbus_clkn]

#NET "lbus_rstn"   LOC="AA13" |IOSTANDARD=LVCMOS15;

set_property PACKAGE_PIN AA13 [get_ports lbus_rstn]
set_property IOSTANDARD LVCMOS15 [get_ports lbus_rstn]


#NET "lbus_do<0>"  LOC="V4"   |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN V4 [get_ports {lbus_do[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[0]}]
#set_property DRIVE 2 [get_ports {lbus_do[0]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[0]}]

#NET "lbus_do<1>"  LOC="V2"   |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN V2 [get_ports {lbus_do[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[1]}]
#set_property DRIVE 2 [get_ports {lbus_do[1]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[1]}]

#NET "lbus_do<2>"  LOC="W1"   |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN W1 [get_ports {lbus_do[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[2]}]
#set_property DRIVE 2 [get_ports {lbus_do[2]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[2]}]

#NET "lbus_do<3>"  LOC="AB1"  |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN AB1 [get_ports {lbus_do[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[3]}]
#set_property DRIVE 2 [get_ports {lbus_do[3]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[3]}]

#NET "lbus_do<4>"  LOC="Y3"   |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN Y3 [get_ports {lbus_do[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[4]}]
#set_property DRIVE 2 [get_ports {lbus_do[4]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[4]}]

#NET "lbus_do<5>"  LOC="U7"   |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN U7 [get_ports {lbus_do[5]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[5]}]
#set_property DRIVE 2 [get_ports {lbus_do[5]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[5]}]

#NET "lbus_do<6>"  LOC="V3"   |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN V3 [get_ports {lbus_do[6]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[6]}]
#set_property DRIVE 2 [get_ports {lbus_do[6]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[6]}]

#NET "lbus_do<7>"  LOC="AF10" |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN AF10 [get_ports {lbus_do[7]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[7]}]
#set_property DRIVE 2 [get_ports {lbus_do[7]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[7]}]

#NET "lbus_do<8>"  LOC="AC13" |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN AC13 [get_ports {lbus_do[8]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[8]}]
#set_property DRIVE 2 [get_ports {lbus_do[8]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[8]}]

#NET "lbus_do<9>"  LOC="AE12" |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN AE12 [get_ports {lbus_do[9]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[9]}]
#set_property DRIVE 2 [get_ports {lbus_do[9]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[9]}]

#NET "lbus_do<10>" LOC="U6"   |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN U6 [get_ports {lbus_do[10]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[10]}]
#set_property DRIVE 2 [get_ports {lbus_do[10]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[10]}]

#NET "lbus_do<11>" LOC="AE13" |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN AE13 [get_ports {lbus_do[11]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[11]}]
#set_property DRIVE 2 [get_ports {lbus_do[11]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[11]}]

#NET "lbus_do<12>" LOC="AA10" |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN AA10 [get_ports {lbus_do[12]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[12]}]
#set_property DRIVE 2 [get_ports {lbus_do[12]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[12]}]

#NET "lbus_do<13>" LOC="AB12" |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN AB12 [get_ports {lbus_do[13]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[13]}]
#set_property DRIVE 2 [get_ports {lbus_do[13]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[13]}]

#NET "lbus_do<14>" LOC="AA4"  |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN AA4 [get_ports {lbus_do[14]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[14]}]
#set_property DRIVE 2 [get_ports {lbus_do[14]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[14]}]

#NET "lbus_do<15>" LOC="AE8"  |IOSTANDARD=LVCMOS15 |SLEW=QUIETIO |DRIVE=2;

set_property PACKAGE_PIN AE8 [get_ports {lbus_do[15]}]
set_property IOSTANDARD LVCMOS15 [get_ports {lbus_do[15]}]
#set_property DRIVE 2 [get_ports {lbus_do[15]}]
#set_property SLEW QUIETIO [get_ports {lbus_do[15]}]

#NET "lbus_wrn"    LOC="AD10" |IOSTANDARD=LVCMOS15;

set_property PACKAGE_PIN AD10 [get_ports lbus_wrn]
set_property IOSTANDARD LVCMOS15 [get_ports lbus_wrn]

#NET "lbus_rdn"    LOC="Y13"  |IOSTANDARD=LVCMOS15;

set_property PACKAGE_PIN Y13 [get_ports lbus_rdn]
set_property IOSTANDARD LVCMOS15 [get_ports lbus_rdn]

########################################
# Spartan-6 HRIC (LVCMOS25 or LVDS_25) #
########################################

#NET "lbus_di_a<0>"   LOC="T22" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN T22 [get_ports {lbus_di_a[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[0]}]

#NET "lbus_di_a<1>"   LOC="M24" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN M24 [get_ports {lbus_di_a[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[1]}]

#NET "lbus_di_a<2>"   LOC="K25" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN K25 [get_ports {lbus_di_a[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[2]}]

#NET "lbus_di_a<3>"   LOC="R26" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN R26 [get_ports {lbus_di_a[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[3]}]

#NET "lbus_di_a<4>"   LOC="M25" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN M25 [get_ports {lbus_di_a[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[4]}]

#NET "lbus_di_a<5>"   LOC="U17" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN U17 [get_ports {lbus_di_a[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[5]}]

#NET "lbus_di_a<6>"   LOC="N26" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN N26 [get_ports {lbus_di_a[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[6]}]

#NET "lbus_di_a<7>"   LOC="R16" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN R16 [get_ports {lbus_di_a[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[7]}]

#NET "lbus_di_a<8>"   LOC="T20" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN T20 [get_ports {lbus_di_a[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[8]}]

#NET "lbus_di_a<9>"   LOC="R22" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN R22 [get_ports {lbus_di_a[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[9]}]

#NET "lbus_di_a<10>"  LOC="M21" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN M21 [get_ports {lbus_di_a[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[10]}]

#NET "lbus_di_a<11>"  LOC="T24" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN T24 [get_ports {lbus_di_a[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[11]}]

#NET "lbus_di_a<12>"  LOC="P23" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN P23 [get_ports {lbus_di_a[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[12]}]

#NET "lbus_di_a<13>"  LOC="N21" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN N21 [get_ports {lbus_di_a[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[13]}]

#NET "lbus_di_a<14>"  LOC="R21" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN R21 [get_ports {lbus_di_a[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[14]}]

#NET "lbus_di_a<15>"  LOC="N18" |IOSTANDARD=LVCMOS25;

set_property PACKAGE_PIN N18 [get_ports {lbus_di_a[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lbus_di_a[15]}]

# PLACEMENT CONSTRAINTS

# SET AES PBLOCK
create_pblock pblock_ENC
resize_pblock [get_pblocks pblock_ENC] -add {SLICE_X36Y209:SLICE_X51Y240}

# ADD AES IN THE PBLOCK
add_cells_to_pblock [get_pblocks pblock_ENC] [get_cells -quiet [list AES_Comp]]

# DON'T PUT ANYTHING IN THE AES PBLOCK
set_property EXCLUDE_PLACEMENT 1 [get_pblocks pblock_ENC]

# VIVADO, STOP TOUCHING MY AES
set_property DONT_TOUCH true [get_cells AES_Comp]

 # SET SENSOR PBLOCK
create_pblock pblock_SENSOR
add_cells_to_pblock [get_pblocks pblock_SENSOR] [get_cells {sensor_top/ID_coarse_s_reg[*] sensor_top/ID_fine_s_reg[*] sensor_top/* sensor_fifo/*}]
resize_pblock [get_pblocks pblock_SENSOR] -add {SLICE_X56Y200:SLICE_X71Y249}
set_property LOC RAMB36_X3Y40 [get_cells sensor_fifo/fifo/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/gbm.gbmg.gbmga.ngecc.bmg/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[0].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.SDP.WIDE_PRIM36_NO_ECC.ram]
set_property LOC RAMB36_X3Y41 [get_cells sensor_fifo/fifo/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.mem/gbm.gbmg.gbmga.ngecc.bmg/inst_blk_mem_gen/gnbram.gnativebmg.native_blk_mem_gen/valid.cstr/ramloop[1].ram.r/prim_noinit.ram/DEVICE_7SERIES.NO_BMM_INFO.SDP.WIDE_PRIM36_NO_ECC.ram]

# DON'T PUT ANYTHING IN THE SENSOR PBLOCK
set_property EXCLUDE_PLACEMENT 1 [get_pblocks pblock_SENSOR]

# SET SENSOR ORIGIN
set_property LOC SLICE_X56Y200 [get_cells sensor_top/sensor/sensor_instance/coarse_init]

# VIVADO, STOP TOUCHING MY SENSOR
set_property DONT_TOUCH true [get_cells sensor_top/sensor/sensor_instance/*]

# PBLOCK FOR OTHER LOGIC (FSM)
create_pblock others
add_cells_to_pblock [get_pblocks others] [get_cells lbus*]
add_cells_to_pblock [get_pblocks others] [get_cells mk_clkrst/u20/*]
add_cells_to_pblock [get_pblocks others] [get_cells {lbus_if FSM  clk_generator reset_gen i_0}]
resize_pblock [get_pblocks others] -add {SLICE_X6Y0:SLICE_X105Y25}

# IGNORE TIMING IN SENSOR
set_false_path -from [get_clocks sensor_clk_clk_generator] -to [get_pins {sensor_top/sensor/sensor_instance/sensor_o_regs[*].obs_regs/D}]
set_false_path -from [get_clocks aes_clk_clk_generator] -to [get_pins {sensor_top/sensor/sensor_instance/sensor_o_regs[*].obs_regs/D}]



